
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dietassistant
    username: root
    password: 111111
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: 111111
      database: 3

dietassistant:
  jwt:
    ttl: 7200000000
    secretkey: zhuay
    userid: userId
    usertoken: token


