---
--- Generated by Luanalysis
--- Created by zhuayang.
--- DateTime: 2024/8/24 15:46
---
local dataKey = ARGV[1]
local deleteTime = ARGV[2]
local nowTime = redis.call("get", dataKey)
if deleteTime == nowTime then
    redis.call('set', dataKey, "")
end