---
--- Generated by Luanalysis
--- Created by zhuayang.
--- DateTime: 2024/8/24 15:46
---
local dataKey = ARGV[1]
local deleteTime = ARGV[2]
local nowDeleteTime = redis.call("get", dataKey)
if nowDeleteTime == "" or deleteTime > nowDeleteTime then
    local setResult = redis.call("set", dataKey, deleteTime)
    if setResult == "OK" then
        return 1  -- SET 命令执行成功
    else
        return 0  -- SET 命令执行失败
    end
end
return 1  -- SET 命令执行成功